version: '3.8'
services:
  node:
    container_name: server
    build: .
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: volume
        target: /app/node_modules